version: '3'

services:
  backend:
    depends_on:
      - postgres
    image: new_python
    env_file:
      - .env
    ports:
      - "8001:8000"
  postgres:
    image: postgres:11.0-alpine
    env_file:
      - .env
#    command:
#      - migra
#    ports:
#      - "5433:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
#  nginx:
##    depends_on:
##      - backend
#    image: nginx
#    ports:
#      - "8000:80"
volumes:
  pg-data: