version: '3.8'

services:
  nginx:
    depends_on:
      - backend
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./static:/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  backend:
    image: new_python
    build: .
    env_file:
      - .env
    ports:
      - "8001:8000"
    depends_on:
      - migration
      - collectstatic
      - postgres
  collectstatic:
    image: new_python
    build: .
    command: python /app/manage.py collectstatic --noinput
    volumes:
      - ./static:/app/static
  postgres:
    image: postgres:11.0-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  migration:
    image: new_python
    build: .
    command: python /app/manage.py migrate --noinput
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  pg-data:
